### PR TITLE
Prevent arguments from being interpreted as options

### PR DESCRIPTION
**Pull request by kidonng**
User inputs, file names and commands can contain leading hypens (`--`), which may cause errors or the function not working.

Examples where fzf.fish would error:
- the cursor is over the token --something when the user executes find file
- the selected changed path from git status is -folder
- the selected command is --function

The solution is to delineate the end of options with --, which is a POSIX specification defined in https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02 (guideline 10), which is respected by Fish builtins. After --, the command will always interpret the arguments as positional arguments.

### CODE REVIEW

**Review by PatrickF1 — APPROVED** [review]
Wow some SQL-injection-like bugs you're fixing here. Amazing, didn't even consider these edge cases!

**Comment by PatrickF1** [comment]
Can you link me to documentation that describes how -- fixes it?

**Comment by PatrickF1** [comment]
Doesn't __fzf_search_shell_variables.fish have the same problem?

**Comment by kidonng** [comment]
It's included.

**Comment by PatrickF1** [comment]
I really don't see it...

**Comment by PatrickF1** [comment]
@kidonng Oh LOL I typoed. You probably thought I was crazy. I meant __fzf_search_git_status.fish

**Comment by kidonng** [comment]
Right, I forgot that it will insert paths eventually.

**Comment by PatrickF1** [comment]
Nice, thanks! I was about to ask why you didn't add `--` to all the string commands but then I realized all the lines will always start with a space and a letter (e.g. ` M functions/file.fish` so there's no need. Good thing you wrote the code first!

**Pull request merged**
