### PR TITLE
[Search git log] include diff stats in preview

### PR DESCRIPTION
**Pull request by NextAlone**

### CODE REVIEW

**Comment by PatrickF1** [comment]
Could you include a screenshot and explain why you think this should be added?

**Comment by NextAlone** [comment]
> Could you include a screenshot and explain why you think this should be added?

If one commit is huge, an overview on the top maybe helpful to quickly get which files were changed.
image

**Comment by PatrickF1** [comment]
Did you test this on smaller width screens? I see --stat has a width parameter and i wonder if we should limit it

**Comment by NextAlone** [comment]
> Did you test this on smaller width screens? I see --stat has a width parameter and i wonder if we should limit it
It works good, i think width is not needed
image

**Review by PatrickF1 — APPROVED** [review]
Ok great! Thanks for testing it for me.

**Comment by PatrickF1** [comment]
Oh wait how come you also added `--oneline`?

**Comment by PatrickF1** [comment]
Oh I see, is it because you are running two git show commands, one on top of the other, and the first one is just for the diff so you want a short summary of the commit?

**Comment by PatrickF1** [comment]
Ok I suspect there's a way to run git show to show both the stats and the diff itself. I'll look into it if you'd like.

**Comment by NextAlone** [comment]
> Oh I see, is it because you are running two git show commands, one on top of the other, and the first one is just for the diff so you want a short summary of the commit?

Yes, you are right.

**Comment by NextAlone** [comment]
> Ok I suspect there's a way to run git show to show both the stats and the diff itself. I'll look into it if you'd like.

I tried looking for it, but couldn't find it. It would be nice if there was a way to show them together.

**Comment by PatrickF1** [comment]
git show HEAD --stat --patch seems to work. Can you try it out?

**Comment by NextAlone** [comment]
> git show HEAD --stat --patch seems to work. Can you try it out?

It works, and --patch-with-stat the same.

image

**Comment by PatrickF1** [comment]
Thank you @NextAlone for this great contribution!

**Comment by NextAlone** [comment]
> Thank you @NextAlone for this great contribution!

And thanks for your work too.

**Pull request merged**
