### PR TITLE
Add git diff preview to Modified paths function

### PR DESCRIPTION
**Pull request by kidonng**
Inspired by [forgit](https://github.com/wfxr/forgit):

image

In fact this is the only function without a preview window now.

### CODE REVIEW

**Comment by PatrickF1** [comment]
Hmm there was a similar PR opened not too long ago https://github.com/PatrickF1/fzf.fish/pull/124. My issue with it was that the user can't tell whether the diff is staging vs HEAD or worktree vs HEAD. What do you think?

**Comment by kidonng** [comment]
Thanks for the pointer. I didn't read that PR throughoutly, but this PR is the same as what you get with regular `git diff`, which should not be confusing.

**Comment by PatrickF1** [comment]
Here's the main thing to read from that PR
Screen Shot 2021-03-22 at 10 46 34 AM

**Comment by PatrickF1** [comment]
See https://github.com/PatrickF1/fzf.fish/pull/124#issuecomment-812622468. LMK if you'd want to work on it. I'm currently biased to letting Quentin finish his work since he came up with the idea first and his PR is more polished.

**Comment by PatrickF1** [comment]
@kidonng A similar PR, #237, has been merged!

**Pull request closed without merging**
