### PR TITLE
Improve instructions readability

### PR DESCRIPTION
**Pull request by jorgebucaran**
WIP: Just small tweaks.

### CODE REVIEW

**Comment by patrickf3139** [comment]
I'm liking the changes so far!

**Comment by jorgebucaran** [comment]
Which one do you prefer from:

- `Ctrl+f`, or
- Ctrl＋<kbd>F</kbd>

**Comment by patrickf3139** [comment]
Second one.

**Comment by jorgebucaran** [comment]
@PatrickF1 Sorry it took me so long to get back to this. I think I'm done. 💯

**Comment by PatrickF1** [comment]
Wow this is well worth the wait 🎉
Thank you Jorge! This is a great upgrade

**Review by PatrickF1 — APPROVED** [review]

**Pull request merged**
